/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppConnecting: typeof import('./components/AppConnecting.vue')['default']
    BApp: typeof import('./../node_modules/@advjs/blender-ui/client/components/BApp.vue')['default']
    BaseButton: typeof import('./../node_modules/@advjs/blender-ui/client/components/BaseButton.vue')['default']
    'BaseButton.story': typeof import('./../node_modules/@advjs/blender-ui/client/components/BaseButton.story.vue')['default']
    BCheckbox: typeof import('./../node_modules/@advjs/blender-ui/client/components/BCheckbox/BCheckbox.vue')['default']
    'BCheckbox.story': typeof import('./../node_modules/@advjs/blender-ui/client/components/BCheckbox/BCheckbox.story.vue')['default']
    BIconButton: typeof import('./../node_modules/@advjs/blender-ui/client/components/BIconButton/BIconButton.vue')['default']
    'BIconButton.story': typeof import('./../node_modules/@advjs/blender-ui/client/components/BIconButton/BIconButton.story.vue')['default']
    BNumberField: typeof import('./../node_modules/@advjs/blender-ui/client/components/BNumberField/BNumberField.vue')['default']
    'BNumberField.story': typeof import('./../node_modules/@advjs/blender-ui/client/components/BNumberField/BNumberField.story.vue')['default']
    BPanel: typeof import('./../node_modules/@advjs/blender-ui/client/components/BPanel/BPanel.vue')['default']
    'BPanel.story': typeof import('./../node_modules/@advjs/blender-ui/client/components/BPanel/BPanel.story.vue')['default']
    BProperty: typeof import('./../node_modules/@advjs/blender-ui/client/components/BProperty/BProperty.vue')['default']
    'BProperty.story': typeof import('./../node_modules/@advjs/blender-ui/client/components/BProperty/BProperty.story.vue')['default']
    BSelectMenu: typeof import('./../node_modules/@advjs/blender-ui/client/components/BSelectMenu/BSelectMenu.vue')['default']
    'BSelectMenu.story': typeof import('./../node_modules/@advjs/blender-ui/client/components/BSelectMenu/BSelectMenu.story.vue')['default']
    BSelectOption: typeof import('./../node_modules/@advjs/blender-ui/client/components/BSelectMenu/BSelectOption.vue')['default']
    BSlider: typeof import('./../node_modules/@advjs/blender-ui/client/components/BSlider/BSlider.vue')['default']
    'BSlider.story': typeof import('./../node_modules/@advjs/blender-ui/client/components/BSlider/BSlider.story.vue')['default']
    BTextField: typeof import('./../node_modules/@advjs/blender-ui/client/components/BTextField/BTextField.vue')['default']
    'BTextField.story': typeof import('./../node_modules/@advjs/blender-ui/client/components/BTextField/BTextField.story.vue')['default']
    BTree: typeof import('./../node_modules/@advjs/blender-ui/client/components/BTree/BTree.vue')['default']
    'BTree.story': typeof import('./../node_modules/@advjs/blender-ui/client/components/BTree/BTree.story.vue')['default']
    BTreeNode: typeof import('./../node_modules/@advjs/blender-ui/client/components/BTree/BTreeNode.vue')['default']
    GalaceanLogo: typeof import('./components/GalaceanLogo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputWithCopy: typeof import('./components/ui/InputWithCopy.vue')['default']
    Meow: typeof import('./../node_modules/@advjs/blender-ui/client/components/Meow.vue')['default']
    Notification: typeof import('./components/ui/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WaitForConnection: typeof import('./components/WaitForConnection.vue')['default']
  }
}
